// flow-typed signature: 5b23a3b7b0906c1b38b4df52c263935e
// flow-typed version: <<STUB>>/babel-plugin-transform-export-extensions_v^6.22.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-export-extensions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-export-extensions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-export-extensions/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-export-extensions/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-export-extensions/lib/index'>;
}
