// flow-typed signature: 1d5163354c8252718882399231c41194
// flow-typed version: <<STUB>>/concat_v^1.0.3/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'concat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'concat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'concat/test/folder/a' {
  declare module.exports: any;
}

declare module 'concat/test/folder/b' {
  declare module.exports: any;
}

declare module 'concat/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'concat/index' {
  declare module.exports: $Exports<'concat'>;
}
declare module 'concat/index.js' {
  declare module.exports: $Exports<'concat'>;
}
declare module 'concat/test/folder/a.js' {
  declare module.exports: $Exports<'concat/test/folder/a'>;
}
declare module 'concat/test/folder/b.js' {
  declare module.exports: $Exports<'concat/test/folder/b'>;
}
declare module 'concat/test/test.js' {
  declare module.exports: $Exports<'concat/test/test'>;
}
