// flow-typed signature: b1116fe2595719d0e58e19d292ca870e
// flow-typed version: <<STUB>>/xendit-js-node_v^0.1.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xendit-js-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xendit-js-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xendit-js-node/src/card' {
  declare module.exports: any;
}

declare module 'xendit-js-node/src/utils/credit_card_util' {
  declare module.exports: any;
}

declare module 'xendit-js-node/src/utils/request_util' {
  declare module.exports: any;
}

declare module 'xendit-js-node/src/xendit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xendit-js-node/src/card.js' {
  declare module.exports: $Exports<'xendit-js-node/src/card'>;
}
declare module 'xendit-js-node/src/utils/credit_card_util.js' {
  declare module.exports: $Exports<'xendit-js-node/src/utils/credit_card_util'>;
}
declare module 'xendit-js-node/src/utils/request_util.js' {
  declare module.exports: $Exports<'xendit-js-node/src/utils/request_util'>;
}
declare module 'xendit-js-node/src/xendit.js' {
  declare module.exports: $Exports<'xendit-js-node/src/xendit'>;
}
